---
title: "Automatic Statistical Identification in Complex Spectra (ASICS)"
author: "Gaëlle Lefort, Rémi Servien and Nathalie Villa-Vialaneix"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
package: ASICS
vignette: >
  %\VignetteIndexEntry{ASICS}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

## Package description 
The **R** package `ASICS` is a fully automated procedure to identify and 
quantify metabolites in $^1$H 1D-NMR spectra of biological mixtures 
(Tardivel *et al.*, 2017). It will enable empowering NMR-based metabolomics by 
quickly and accurately helping experts to obtain metabolic profiles. In addition
to the quantification method, several functions allowing spectrum 
preprocessing or statistical analyses of quantified metabolites are available.

The full ASICS User's Guide is available after installing the package. It can be
opened with:

```{r userguide}
library(ASICS)
ASICSUsersGuide(view = FALSE)
```


## References
Tardivel P., Canlet C., Lefort G., Tremblay-Franco M., Debrauwer L., Concordet 
D., Servien R. (2017). ASICS: an automatic method for identification and 
quantification of metabolites in complex 1D 1H NMR spectra. *Metabolomics*,
**13**(10): 109. https://doi.org/10.1007/s11306-017-1244-5

